### ISSUE TITLE
Unable to open SQLite database

### ISSUE THREAD

**Issue by MehediH** [mikeyk/node-imessage-codes#1]
Hey Mike,

Thanks for this script! It's super annoying having to manually copy 2FA codes from my phone so hopefully, this will speed things up.

Unfortunately, I couldn't get this script to work. At first, I was simply getting `UnhandledPromiseRejectionWarning` errors because there is no `catch` block on the `open()` at line 43. 

After adding the catch, it showed some more details on the error and got rid of the promise rejection errors:

```
[Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}
```

Let me know if you need more details!

**Comment by mikeyk** [comment]
thanks for the report! can you pull the latest code? I changed the open flag to read-only (in case there's a permissions issue)

**Comment by MehediH** [comment]
thanks! still getting the same error unfortunately

**Comment by JulianTenschert** [comment]
Hey Mike, 

Thanks for this awesome script!

I had the same error as Mehedi.

The solution was to enable "Full Disk Access" in the macOS settings (for iTerm2):
https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/

Now it works like a charm. 

I'm looking forward to your next projects. 

Thanks again,
Julian

**Comment by mikeyk** [comment]
Thank you! I added instruction to the README.
